package cn.com.dhcc.emr.metaservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-02-15T16:45:18.528+08:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://www.dhcc.com.cn/emr/metaservice", name = "ImageBOItemInfoSoap")
@XmlSeeAlso({ObjectFactory.class, cn.com.dhcc.epr.metaservice.imageeitemdataset.ObjectFactory.class})
public interface ImageBOItemInfoSoap {

    @WebMethod(operationName = "UpdateSequences", action = "http://www.dhcc.com.cn/emr/metaservice/EMRservice.Image.BOItem.UpdateSequences")
    @RequestWrapper(localName = "UpdateSequences", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice", className = "cn.com.dhcc.emr.metaservice.UpdateSequences")
    @ResponseWrapper(localName = "UpdateSequencesResponse", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice", className = "cn.com.dhcc.emr.metaservice.UpdateSequencesResponse")
    @WebResult(name = "UpdateSequencesResult", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice")
    public java.lang.String updateSequences(
        @WebParam(name = "argStr", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice")
        java.lang.String argStr
    );

    @WebMethod(operationName = "GetItemsByTreeID", action = "http://www.dhcc.com.cn/emr/metaservice/EMRservice.Image.BOItem.GetItemsByTreeID")
    @RequestWrapper(localName = "GetItemsByTreeID", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice", className = "cn.com.dhcc.emr.metaservice.GetItemsByTreeID")
    @ResponseWrapper(localName = "GetItemsByTreeIDResponse", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice", className = "cn.com.dhcc.emr.metaservice.GetItemsByTreeIDResponse")
    @WebResult(name = "GetItemsByTreeIDResult", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice")
    public cn.com.dhcc.emr.metaservice.Items getItemsByTreeID(
        @WebParam(name = "AImageCatID", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice")
        java.lang.String aImageCatID
    );

    @WebMethod(operationName = "Create", action = "http://www.dhcc.com.cn/emr/metaservice/EMRservice.Image.BOItem.Create")
    @RequestWrapper(localName = "Create", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice", className = "cn.com.dhcc.emr.metaservice.Create")
    @ResponseWrapper(localName = "CreateResponse", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice", className = "cn.com.dhcc.emr.metaservice.CreateResponse")
    @WebResult(name = "CreateResult", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice")
    public java.lang.String create(
        @WebParam(name = "AEImageItem", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice")
        cn.com.dhcc.emr.metaservice.EItem aeImageItem
    );

    @WebMethod(operationName = "CheckCodeExist", action = "http://www.dhcc.com.cn/emr/metaservice/EMRservice.Image.BOItem.CheckCodeExist")
    @RequestWrapper(localName = "CheckCodeExist", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice", className = "cn.com.dhcc.emr.metaservice.CheckCodeExist")
    @ResponseWrapper(localName = "CheckCodeExistResponse", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice", className = "cn.com.dhcc.emr.metaservice.CheckCodeExistResponse")
    @WebResult(name = "CheckCodeExistResult", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice")
    public java.lang.String checkCodeExist(
        @WebParam(name = "Acode", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice")
        java.lang.String acode
    );

    @WebMethod(operationName = "CheckImageItemPublished", action = "http://www.dhcc.com.cn/emr/metaservice/EMRservice.Image.BOItem.CheckImageItemPublished")
    @RequestWrapper(localName = "CheckImageItemPublished", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice", className = "cn.com.dhcc.emr.metaservice.CheckImageItemPublished")
    @ResponseWrapper(localName = "CheckImageItemPublishedResponse", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice", className = "cn.com.dhcc.emr.metaservice.CheckImageItemPublishedResponse")
    @WebResult(name = "CheckImageItemPublishedResult", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice")
    public java.lang.String checkImageItemPublished(
        @WebParam(name = "AFigureID", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice")
        java.lang.String aFigureID,
        @WebParam(name = "AFigureType", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice")
        java.lang.String aFigureType
    );

    @WebMethod(operationName = "DeleteByID", action = "http://www.dhcc.com.cn/emr/metaservice/EMRservice.Image.BOItem.DeleteByID")
    @RequestWrapper(localName = "DeleteByID", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice", className = "cn.com.dhcc.emr.metaservice.DeleteByID")
    @ResponseWrapper(localName = "DeleteByIDResponse", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice", className = "cn.com.dhcc.emr.metaservice.DeleteByIDResponse")
    @WebResult(name = "DeleteByIDResult", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice")
    public java.lang.String deleteByID(
        @WebParam(name = "AImageItemID", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice")
        java.lang.String aImageItemID
    );

    @WebMethod(operationName = "GetChildCountByTreeID", action = "http://www.dhcc.com.cn/emr/metaservice/EMRservice.Image.BOItem.GetChildCountByTreeID")
    @RequestWrapper(localName = "GetChildCountByTreeID", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice", className = "cn.com.dhcc.emr.metaservice.GetChildCountByTreeID")
    @ResponseWrapper(localName = "GetChildCountByTreeIDResponse", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice", className = "cn.com.dhcc.emr.metaservice.GetChildCountByTreeIDResponse")
    @WebResult(name = "GetChildCountByTreeIDResult", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice")
    public java.lang.String getChildCountByTreeID(
        @WebParam(name = "AImageTreeID", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice")
        java.lang.String aImageTreeID
    );

    @WebMethod(operationName = "GetByImageTreeID", action = "http://www.dhcc.com.cn/emr/metaservice/EMRservice.Image.BOItem.GetByImageTreeID")
    @RequestWrapper(localName = "GetByImageTreeID", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice", className = "cn.com.dhcc.emr.metaservice.GetByImageTreeID")
    @ResponseWrapper(localName = "GetByImageTreeIDResponse", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice", className = "cn.com.dhcc.emr.metaservice.GetByImageTreeIDResponse")
    @WebResult(name = "GetByImageTreeIDResult", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice")
    public cn.com.dhcc.emr.metaservice.EItemDataSet getByImageTreeID(
        @WebParam(name = "AImageTreeID", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice")
        java.lang.String aImageTreeID
    );

    @WebMethod(operationName = "GetEntity", action = "http://www.dhcc.com.cn/emr/metaservice/EMRservice.Image.BOItem.GetEntity")
    @RequestWrapper(localName = "GetEntity", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice", className = "cn.com.dhcc.emr.metaservice.GetEntity")
    @ResponseWrapper(localName = "GetEntityResponse", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice", className = "cn.com.dhcc.emr.metaservice.GetEntityResponse")
    @WebResult(name = "GetEntityResult", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice")
    public cn.com.dhcc.emr.metaservice.EItem getEntity(
        @WebParam(name = "AImgeItemID", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice")
        java.lang.String aImgeItemID
    );

    @WebMethod(operationName = "Update", action = "http://www.dhcc.com.cn/emr/metaservice/EMRservice.Image.BOItem.Update")
    @RequestWrapper(localName = "Update", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice", className = "cn.com.dhcc.emr.metaservice.Update")
    @ResponseWrapper(localName = "UpdateResponse", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice", className = "cn.com.dhcc.emr.metaservice.UpdateResponse")
    @WebResult(name = "UpdateResult", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice")
    public java.lang.String update(
        @WebParam(name = "AEImageItem", targetNamespace = "http://www.dhcc.com.cn/emr/metaservice")
        cn.com.dhcc.emr.metaservice.EItem aeImageItem
    );
}
